# Data Science Nigeria 2019 Challenge #1: Insurance Prediction

## Imports

In [1]:
# import ML libraries
# You may need to install some of these libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from catboost import CatBoostClassifier
from lightgbm import LGBMClassifier
from rgf.sklearn import RGFClassifier
from sklearn.ensemble import IsolationForest, RandomForestClassifier, VotingClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import confusion_matrix, classification_report, roc_auc_score
from sklearn.model_selection import cross_val_score, RepeatedStratifiedKFold, StratifiedKFold, train_test_split
from sklearn.svm import SVC
from sklearn.ensemble import VotingClassifier
from xgboost import XGBClassifier

sns.set()
%matplotlib inline
np.random.seed(23)

pd.set_option('max_columns', 500)
# pd.set_option('max_rows', 500)
pd.set_option('max_colwidth', 500)

In [2]:
# import the data
train = pd.read_csv('data/train_data.csv')
test = pd.read_csv('data/test_data.csv')
vd = pd.read_csv('data/VariableDescription.csv')
submit = pd.read_csv('data/sample_submission.csv')

In [3]:
train.head(10)

,Customer Id,YearOfObservation,Insured_Period,Residential,Building_Painted,Building_Fenced,Garden,Settlement,Building Dimension,Building_Type,Date_of_Occupancy,NumberOfWindows,Geo_Code,Claim
0,H14663,2013,1.0,0,N,V,V,U,290.0,1,1960.0,.,1053,0
1,H2037,2015,1.0,0,V,N,O,R,490.0,1,1850.0,4,1053,0
2,H3802,2014,1.0,0,N,V,V,U,595.0,1,1960.0,.,1053,0
3,H3834,2013,1.0,0,V,V,V,U,2840.0,1,1960.0,.,1053,0
4,H5053,2014,1.0,0,V,N,O,R,680.0,1,1800.0,3,1053,0
5,H4977,2012,1.0,0,V,N,O,R,535.0,1,1980.0,3,1143,0
6,H7390,2012,1.0,0,N,V,V,U,2830.0,1,1988.0,.,1143,0
7,H14488,2015,1.0,0,N,V,V,U,4952.0,1,1988.0,.,1160,0
8,H19355,2014,1.0,0,V,N,O,R,2735.0,1,2013.0,3,1173,1
9,H18601,2015,1.0,0,V,N,O,R,520.0,1,2011.0,2,1224,0

In [4]:
test.head()

,Customer Id,YearOfObservation,Insured_Period,Residential,Building_Painted,Building_Fenced,Garden,Settlement,Building Dimension,Building_Type,Date_of_Occupancy,NumberOfWindows,Geo_Code
0,H11920,2013,1.000000,0,V,N,O,R,300.0,1,1960.0,3,3310
1,H11921,2016,0.997268,0,V,N,O,R,300.0,1,1960.0,3,3310
2,H9805,2013,0.369863,0,V,V,V,U,790.0,1,1960.0,.,3310
3,H7493,2014,1.000000,0,V,N,O,R,1405.0,1,2004.0,3,3321
4,H7494,2016,1.000000,0,V,N,O,R,1405.0,1,2004.0,3,3321

In [5]:
vd.head(50)

,Variable,Description
0,Customer Id,Identification number for the Policy holder
1,YearOfObservation,year of observation for the insured policy
2,Insured_Period,"duration of insurance policy in Olusola Insurance. (Ex: Full year insurance, Policy Duration = 1; 6 months = 0.5"
3,Residential,is the building a residential building or not
4,Building_Painted,"is the building painted or not (N-Painted, V-Not Painted)"
5,Building_Fenced,"is the building fence or not (N-Fenced, V-Not Fenced)"
6,Garden,building has garden or not (V-has garden; O-no garden)
7,Settlement,Area where the building is located. (R- rural area; U- urban area)
8,Building Dimension,Size of the insured building in m2
9,Building_Type,"The type of building (Type 1, 2, 3, 4)"
10,Date_of_Occupancy,date building was first occupied
11,NumberOfWindows,number of windows in the building
12,Geo Code,Geographical Code of the Insured building
13,Claim,"target variable. (0: no claim, 1: at least one claim over insured period)."

In [6]:
train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7160 entries, 0 to 7159
Data columns (total 14 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Customer Id         7160 non-null   object
 1   YearOfObservation   7160 non-null   int64
 2   Insured_Period      7160 non-null   float64
 3   Residential         7160 non-null   int64
 4   Building_Painted    7160 non-null   object
 5   Building_Fenced     7160 non-null   object
 6   Garden              7153 non-null   object
 7   Settlement          7160 non-null   object
 8   Building Dimension  7054 non-null   float64
 9   Building_Type       7160 non-null   int64
 10  Date_of_Occupancy   6652 non-null   float64
 11  NumberOfWindows     7160 non-null   object
 12  Geo_Code            7058 non-null   object
 13  Claim               7160 non-null   int64
dtypes: float64(3), int64(4), object(7)
memory usage: 783.2+ KB

In [7]:
test.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3069 entries, 0 to 3068
Data columns (total 13 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Customer Id         3069 non-null   object
 1   YearOfObservation   3069 non-null   int64
 2   Insured_Period      3069 non-null   float64
 3   Residential         3069 non-null   int64
 4   Building_Painted    3069 non-null   object
 5   Building_Fenced     3069 non-null   object
 6   Garden              3065 non-null   object
 7   Settlement          3069 non-null   object
 8   Building Dimension  3056 non-null   float64
 9   Building_Type       3069 non-null   int64
 10  Date_of_Occupancy   2341 non-null   float64
 11  NumberOfWindows     3069 non-null   object
 12  Geo_Code            3056 non-null   object
dtypes: float64(3), int64(3), object(7)
memory usage: 311.8+ KB

In [9]:
submit.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3068 entries, 0 to 3067
Data columns (total 2 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Customer Id  3068 non-null   object
 1   Claim        3068 non-null   int64
dtypes: int64(1), object(1)
memory usage: 48.1+ KB

## Exploratory Data Analysis

In [8]:
# Check for duplicates
train.duplicated().sum()

0

In [9]:
# check for missing values
train.isna().sum()

Customer Id             0
YearOfObservation       0
Insured_Period          0
Residential             0
Building_Painted        0
Building_Fenced         0
Garden                  7
Settlement              0
Building Dimension    106
Building_Type           0
Date_of_Occupancy     508
NumberOfWindows         0
Geo_Code              102
Claim                   0
dtype: int64

In [10]:
test.isna().sum()

Customer Id             0
YearOfObservation       0
Insured_Period          0
Residential             0
Building_Painted        0
Building_Fenced         0
Garden                  4
Settlement              0
Building Dimension     13
Building_Type           0
Date_of_Occupancy     728
NumberOfWindows         0
Geo_Code               13
dtype: int64

In [11]:
# fill missing values
train.fillna(-1, inplace=True, axis=1)
test.fillna(-1, inplace=True, axis=1)

In [12]:
train.isna().sum()

Customer Id           0
YearOfObservation     0
Insured_Period        0
Residential           0
Building_Painted      0
Building_Fenced       0
Garden                0
Settlement            0
Building Dimension    0
Building_Type         0
Date_of_Occupancy     0
NumberOfWindows       0
Geo_Code              0
Claim                 0
dtype: int64

In [17]:
train["Building_Type"].value_counts()

Customer Id


H13164    1
H12617    1
H3093     1
H4666     1
H16353    1
         ..
H17972    1
H15021    1
H15873    1
H6177     1
H17954    1
Name: Customer Id, Length: 7160, dtype: int64


YearOfObservation


2012    1858
2013    1811
2014    1373
2015    1075
2016    1043
Name: YearOfObservation, dtype: int64


Insured_Period


1.000000    5325
0.997268     547
0.000000     165
0.747945      60
0.495890      49
0.832877      28
0.246575      27
0.997260      26
0.994536      24
0.915068      23
0.161644      23
0.084932      22
0.967213      22
0.665753      21
0.983562      17
0.580822      16
0.413699      16
0.328767      13
0.751366      12
0.915301      12
0.748634      12
0.836066      10
0.579235       9
0.248634       9
0.494536       9
0.084699       8
0.251366       8
0.502732       8
0.163934       7
0.167123       6
0.989071       6
0.415301       6
0.334247       6
0.584699       6
0.418033       6
0.986301       6
0.104110       5
0.493151       5
0.333333       5
0.745205       5
0.821918       5
0.581967       5
0.252055       5
0.769863       5
0.920765       5
0.953425       5
0.893151       5
0.912329       4
0.120548       4
0.330601       4
0.695890       4
0.052055       4
0.709589       4
0.497268       4
0.657534       4
0.164384       4
0.838356       4
0.038251       4
0.745902       4
0.504110       4
0.794521       4
0.865753       4
0.912568       4
0.693151       3
0.671233       3
0.021918       3
0.438356       3
0.169863       3
0.271233       3
0.890411       3
0.166667       3
0.666667       3
0.038356       3
0.917808       3
0.882192       3
0.663934       3
0.457534       3
0.868852       3
0.901370       3
0.857534       3
0.158904       3
0.545205       3
0.216438       3
0.468493       3
0.753425       3
0.668493       3
0.476712       3
0.509589       2
0.613699       2
0.674863       2
0.564384       2
0.833333       2
0.964384       2
0.150685       2
0.191257       2
0.517808       2
0.808219       2
0.315068       2
0.452055       2
0.958904       2
0.843836       2
0.068306       2
0.606557       2
0.950685       2
0.060109       2
0.523288       2
0.813699       2
0.780822       2
0.465753       2
0.600000       2
0.431694       2
0.728767       2
0.953552       2
0.632877       2
0.241096       2
0.871233       2
0.884932       2
0.800000       2
0.131507       2
0.802740       2
0.311475       2
0.109589       2
0.989041       2
0.123288       2
0.219178       2
0.293151       2
0.906849       2
0.200000       2
0.189041       2
0.213115       2
0.926027       2
0.682192       2
0.783562       2
0.079452       2
0.087671       2
0.816438       2
0.320548       2
0.713115       2
0.775342       2
0.887671       2
0.510929       2
0.890710       2
0.210959       2
0.464481       2
0.909589       2
0.827869       2
0.016393       2
0.754098       2
0.673973       2
0.142466       2
0.961644       2
0.641096       2
0.235616       2
0.540984       2
0.093151       2
0.065574       2
0.098630       2
0.367123       2
0.539726       2
0.290411       2
0.567123       2
0.942466       2
0.791781       2
0.571038       2
0.846995       2
0.702186       2
0.323288       2
0.263014       2
0.128767       2
0.081967       2
0.482192       2
0.947945       2
0.147541       1
0.956164       1
0.873973       1
0.453552       1
0.663014       1
0.202186       1
0.071038       1
0.646575       1
0.450820       1
0.300546       1
0.224658       1
0.945205       1
0.213699       1
0.380822       1
0.341530       1
0.010929       1
0.792350       1
0.901639       1
0.562842       1
0.874317       1
0.608219       1
0.994521       1
0.934247       1
0.978082       1
0.114754       1
0.479452       1
0.024590       1
0.811475       1
0.032787       1
0.205479       1
0.795082       1
0.928962       1
0.583562       1
0.057534       1
0.630137       1
0.443836       1
0.106849       1
0.909836       1
0.051913       1
0.860274       1
0.521858       1
0.972603       1
0.352459       1
0.237705       1
0.945355       1
0.578082       1
0.180328       1
0.172603       1
0.144809       1
0.393443       1
0.715847       1
0.079235       1
0.819178       1
0.603825       1
0.434426       1
0.301370       1
0.243169       1
0.991781       1
0.789617       1
0.428962       1
0.597260       1
0.153425       1
0.778689       1
0.347945       1
0.153005       1
0.469945       1
0.527322       1
0.175342       1
0.117808       1
0.797814       1
0.710383       1
0.854795       1
0.923288       1
0.046448       1
0.609290       1
0.688525       1
0.049180       1
0.750685       1
0.030055       1
0.120219       1
0.969863       1
0.778082       1
0.259563       1
0.254795       1
0.967123       1
0.295890       1
0.448087       1
0.942623       1
0.841096       1
0.230137       1
0.549180       1
0.194521       1
0.759563       1
0.041096       1
0.822404       1
0.035616       1
0.612022       1
0.196721       1
0.437158       1
0.739726       1
0.002732       1
0.573770       1
0.227397       1
0.295082       1
0.849315       1
0.560109       1
0.680328       1
0.054795       1
0.736986       1
0.308743       1
0.797260       1
0.484932       1
0.030137       1
0.410959       1
0.338798       1
0.303279       1
0.475410       1
0.136986       1
0.652055       1
0.961749       1
0.454795       1
0.819672       1
0.197260       1
0.803279       1
0.720548       1
0.936986       1
0.471233       1
0.480874       1
0.937158       1
0.221918       1
0.734247       1
0.043836       1
0.344262       1
0.621918       1
0.073973       1
0.487671       1
0.526027       1
0.435616       1
0.416438       1
0.956284       1
0.824658       1
0.535519       1
0.024658       1
0.879781       1
0.534247       1
0.345205       1
0.208219       1
0.642077       1
0.950820       1
0.756164       1
0.972678       1
0.546448       1
0.402740       1
0.276712       1
0.882514       1
0.095890       1
0.046575       1
0.731507       1
0.076712       1
0.743169       1
0.327869       1
0.459016       1
0.500000       1
0.855191       1
0.383562       1
0.339726       1
0.193989       1
0.297814       1
0.186301       1
0.827397       1
0.177596       1
0.082192       1
0.633880       1
0.660274       1
0.377049       1
0.172131       1
0.520548       1
0.781421       1
0.158470       1
0.445355       1
0.536986       1
0.245902       1
0.183562       1
0.810959       1
0.336986       1
0.844262       1
0.361644       1
0.805479       1
0.586301       1
0.284932       1
0.372603       1
0.846575       1
0.789041       1
0.420765       1
0.358904       1
0.122951       1
0.931507       1
0.964481       1
0.907104       1
0.547945       1
0.677596       1
0.556164       1
0.543716       1
0.060274       1
0.830137       1
0.594521       1
0.467213       1
0.449315       1
0.838798       1
0.180822       1
0.786301       1
0.767123       1
0.378082       1
0.554645       1
0.698630       1
0.109290       1
0.975342       1
0.249315       1
0.868493       1
0.631148       1
0.704918       1
0.605479       1
0.893443       1
0.260274       1
0.268493       1
0.898630       1
0.887978       1
0.830601       1
0.331507       1
Name: Insured_Period, dtype: int64


Residential


0    4973
1    2187
Name: Residential, dtype: int64


Building_Painted


V    5382
N    1778
Name: Building_Painted, dtype: int64


Building_Fenced


N    3608
V    3552
Name: Building_Fenced, dtype: int64


Garden


O     3602
V     3551
-1       7
Name: Garden, dtype: int64


Settlement


R    3610
U    3550
Name: Settlement, dtype: int64


Building Dimension


400.0     150
500.0     120
300.0     118
450.0     117
600.0     114
         ...
1303.0      1
907.0       1
2445.0      1
924.0       1
4069.0      1
Name: Building Dimension, Length: 2044, dtype: int64


Building_Type


2    3305
1    1716
3    1230
4     909
Name: Building_Type, dtype: int64


Date_of_Occupancy


 1960.0    1818
 1980.0    1155
 1988.0     530
-1.0        508
 1900.0     371
 1970.0     285
 1950.0     245
 1930.0     167
 1920.0     100
 1990.0      98
 2011.0      97
 2009.0      89
 2008.0      74
 2010.0      65
 2012.0      62
 2007.0      58
 1940.0      53
 1975.0      52
 2000.0      52
 1965.0      52
 1850.0      49
 2005.0      37
 2004.0      35
 1985.0      34
 1972.0      33
 2003.0      33
 1978.0      31
 2006.0      31
 1995.0      31
 1910.0      28
 2001.0      27
 2002.0      27
 1974.0      26
 1971.0      25
 1969.0      24
 1800.0      24
 1998.0      22
 1955.0      22
 1979.0      22
 1982.0      21
 1989.0      21
 1973.0      21
 1999.0      20
 1977.0      20
 1983.0      20
 1964.0      18
 1962.0      18
 1870.0      17
 2013.0      17
 1991.0      17
 1890.0      16
 1986.0      15
 1996.0      15
 1958.0      15
 1954.0      15
 1992.0      15
 1976.0      15
 1968.0      14
 1994.0      14
 1981.0      14
 1961.0      14
 1967.0      14
 1959.0      13
 1963.0      12
 1987.0      12
 1945.0      11
 1984.0      11
 1997.0      11
 1957.0      10
 1700.0      10
 1993.0      10
 1880.0      10
 1966.0       9
 2014.0       9
 2015.0       8
 1953.0       7
 1935.0       6
 1956.0       6
 1948.0       6
 1937.0       5
 1951.0       5
 1904.0       5
 1600.0       5
 1949.0       5
 1895.0       4
 1830.0       4
 1898.0       4
 1875.0       4
 1925.0       4
 1947.0       3
 1901.0       3
 1912.0       3
 1750.0       3
 1942.0       3
 1896.0       3
 1936.0       3
 1860.0       3
 1810.0       3
 1907.0       3
 1924.0       2
 2016.0       2
 1903.0       2
 1915.0       2
 1911.0       2
 1893.0       2
 1871.0       2
 1952.0       2
 1913.0       2
 1718.0       2
 1908.0       1
 1820.0       1
 1928.0       1
 1934.0       1
 1927.0       1
 1914.0       1
 1906.0       1
 1939.0       1
 1905.0       1
 1931.0       1
 1864.0       1
 1550.0       1
 1824.0       1
 1946.0       1
 1613.0       1
 1929.0       1
 1902.0       1
 1840.0       1
 1926.0       1
 1938.0       1
 1919.0       1
 1884.0       1
 1780.0       1
 1846.0       1
 1923.0       1
 1545.0       1
Name: Date_of_Occupancy, dtype: int64


NumberOfWindows


   .    3551
4        939
3        844
5        639
2        363
6        306
7        211
8        116
1         75
>=10      67
9         49
Name: NumberOfWindows, dtype: int64


Geo_Code


6088     143
33063    137
6083     113
-1       102
13206     98
        ...
28085      1
42285      1
78217      1
57160      1
30334      1
Name: Geo_Code, Length: 1308, dtype: int64


Claim


0    5526
1    1634
Name: Claim, dtype: int64

## Feature Engineering

In [13]:
train.drop(['Customer Id', 'Geo_Code'], inplace=True, axis=1)
test.drop(['Customer Id', 'Geo_Code'], inplace=True, axis=1)

In [14]:
train['NumberOfWindows'].value_counts()

   .    3551
4        939
3        844
5        639
2        363
6        306
7        211
8        116
1         75
>=10      67
9         49
Name: NumberOfWindows, dtype: int64

In [15]:
# fix number of windows
def fix_windows(x):
    if x == '>=10':
        return 10
    elif x == '   .':
        return -1
    else:
        return int(x)

train['NumberOfWindows'] = train['NumberOfWindows'].apply(fix_windows)
test['NumberOfWindows'] = test['NumberOfWindows'].apply(fix_windows)

In [16]:
train['NumberOfWindows'].value_counts()

-1     3551
 4      939
 3      844
 5      639
 2      363
 6      306
 7      211
 8      116
 1       75
 10      67
 9       49
Name: NumberOfWindows, dtype: int64

In [17]:
# encode categorical variables
combined = train.append(test, ignore_index=True).copy()

In [18]:
combined.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10229 entries, 0 to 10228
Data columns (total 12 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   YearOfObservation   10229 non-null  int64
 1   Insured_Period      10229 non-null  float64
 2   Residential         10229 non-null  int64
 3   Building_Painted    10229 non-null  object
 4   Building_Fenced     10229 non-null  object
 5   Garden              10229 non-null  object
 6   Settlement          10229 non-null  object
 7   Building Dimension  10229 non-null  float64
 8   Building_Type       10229 non-null  int64
 9   Date_of_Occupancy   10229 non-null  float64
 10  NumberOfWindows     10229 non-null  int64
 11  Claim               7160 non-null   float64
dtypes: float64(4), int64(4), object(4)
memory usage: 959.1+ KB

In [19]:
combined = pd.get_dummies(combined)

In [20]:
combined.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10229 entries, 0 to 10228
Data columns (total 17 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   YearOfObservation   10229 non-null  int64
 1   Insured_Period      10229 non-null  float64
 2   Residential         10229 non-null  int64
 3   Building Dimension  10229 non-null  float64
 4   Building_Type       10229 non-null  int64
 5   Date_of_Occupancy   10229 non-null  float64
 6   NumberOfWindows     10229 non-null  int64
 7   Claim               7160 non-null   float64
 8   Building_Painted_N  10229 non-null  uint8
 9   Building_Painted_V  10229 non-null  uint8
 10  Building_Fenced_N   10229 non-null  uint8
 11  Building_Fenced_V   10229 non-null  uint8
 12  Garden_-1           10229 non-null  uint8
 13  Garden_O            10229 non-null  uint8
 14  Garden_V            10229 non-null  uint8
 15  Settlement_R        10229 non-null  uint8
 16  Settlement_U        10229 non-null  uint8
dtypes: float64(4), int64(4), uint8(9)
memory usage: 729.3 KB

In [21]:
train = combined[:7160].copy()
test = combined[7160:].copy()

In [22]:
test.drop('Claim', axis=1, inplace=True)

In [23]:
X = train.drop('Claim', axis=1).copy()
y = train['Claim'].copy()

In [24]:
X.shape, y.shape

((7160, 16), (7160,))

 ## Modelling

Evaluation Metrics for the competition is `roc_auc_score`. Read about it here: [Classification: ROC Curve and AUC](https://developers.google.com/machine-learning/crash-course/classification/roc-and-auc)

In [26]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.1, random_state=5, stratify=y)

### RandomForest

In [29]:
rf = RandomForestClassifier(n_jobs=-1, verbose=5)
rf.fit(X_train, y_train)

predx = rf.predict(X_test)
pred = rf.predict_proba(X_test)
pred = [x[1] for x in pred]

building tree 1 of 100building tree 2 of 100
building tree 3 of 100
building tree 4 of 100

building tree 5 of 100building tree 6 of 100

building tree 7 of 100
building tree 8 of 100
building tree 9 of 100building tree 10 of 100
building tree 11 of 100building tree 12 of 100


building tree 13 of 100
building tree 14 of 100
building tree 15 of 100
building tree 16 of 100
building tree 17 of 100
building tree 18 of 100building tree 19 of 100

building tree 20 of 100building tree 21 of 100

building tree 22 of 100building tree 23 of 100

building tree 24 of 100
building tree 25 of 100building tree 26 of 100
building tree 27 of 100

building tree 28 of 100
building tree 29 of 100
building tree 30 of 100
building tree 31 of 100
building tree 32 of 100
building tree 33 of 100
building tree 34 of 100building tree 35 of 100

building tree 36 of 100
building tree 37 of 100
building tree 38 of 100
building tree 39 of 100building tree 40 of 100

building tree 41 of 100
building tree 42 of 100building tree 43 of 100

building tree 44 of 100
building tree 45 of 100building tree 46 of 100building tree 47 of 100
building tree 48 of 100


building tree 49 of 100
building tree 50 of 100
building tree 51 of 100
building tree 52 of 100
building tree 53 of 100
building tree 54 of 100building tree 55 of 100

building tree 56 of 100
building tree 57 of 100building tree 58 of 100

building tree 59 of 100
building tree 60 of 100
building tree 61 of 100
building tree 62 of 100
building tree 63 of 100
building tree 64 of 100
building tree 65 of 100
building tree 66 of 100
building tree 67 of 100
building tree 68 of 100
building tree 69 of 100building tree 70 of 100

building tree 71 of 100building tree 72 of 100

building tree 73 of 100
building tree 74 of 100
building tree 75 of 100
building tree 76 of 100
building tree 77 of 100
building tree 78 of 100
building tree 79 of 100
building tree 80 of 100
building tree 81 of 100
building tree 82 of 100
building tree 83 of 100
building tree 84 of 100
building tree 85 of 100
building tree 86 of 100
building tree 87 of 100
building tree 88 of 100building tree 89 of 100

building tree 90 of 100
building tree 91 of 100building tree 92 of 100building tree 93 of 100
building tree 94 of 100


building tree 95 of 100
building tree 96 of 100
building tree 97 of 100building tree 98 of 100
building tree 99 of 100
building tree 100 of 100

0.6719455507604921
              precision    recall  f1-score   support

         0.0       0.80      0.90      0.85       553
         1.0       0.43      0.25      0.32       163

    accuracy                           0.75       716
   macro avg       0.62      0.58      0.58       716
weighted avg       0.72      0.75      0.73       716

[Parallel(n_jobs=-1)]: Using backend ThreadingBackend with 8 concurrent workers.
[Parallel(n_jobs=-1)]: Done   2 tasks      | elapsed:    0.0s
[Parallel(n_jobs=-1)]: Done  56 tasks      | elapsed:    0.1s
[Parallel(n_jobs=-1)]: Done 100 out of 100 | elapsed:    0.1s finished
[Parallel(n_jobs=8)]: Using backend ThreadingBackend with 8 concurrent workers.
[Parallel(n_jobs=8)]: Done   2 tasks      | elapsed:    0.0s
[Parallel(n_jobs=8)]: Done  56 tasks      | elapsed:    0.0s
[Parallel(n_jobs=8)]: Done 100 out of 100 | elapsed:    0.0s finished
[Parallel(n_jobs=8)]: Using backend ThreadingBackend with 8 concurrent workers.
[Parallel(n_jobs=8)]: Done   2 tasks      | elapsed:    0.0s
[Parallel(n_jobs=8)]: Done  56 tasks      | elapsed:    0.0s
[Parallel(n_jobs=8)]: Done 100 out of 100 | elapsed:    0.0s finished

In [ ]:
print(roc_auc_score(y_test, pred))
print(classification_report(y_test, predx))

In [30]:
# submission
value = rf.predict_proba(test)
value = [x[1] for x in value]

[Parallel(n_jobs=8)]: Using backend ThreadingBackend with 8 concurrent workers.
[Parallel(n_jobs=8)]: Done   2 tasks      | elapsed:    0.0s
[Parallel(n_jobs=8)]: Done  56 tasks      | elapsed:    0.0s
[Parallel(n_jobs=8)]: Done 100 out of 100 | elapsed:    0.0s finished

In [32]:
test2 = pd.read_csv('data/test_data.csv')

test2['Claim'] = value

submit = test2[['Customer Id', 'Claim']].copy()

In [33]:
submit.to_csv('data/Submission1.csv', index=False)